apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: andrea
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: mguay/ordering-app_auth
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: JWT_SECRET
              value: yJSDVpxKUQ1LSfrnrsLN6r6tmFd1i95I3zGXjpIryO8zoWg7fDmYEnyyCmtKFh2MFd4c7rFjN9wKsiwRXYKZ9BKJ5YHTByQi8Q4
            - name: JWT_EXPIRATION
              value: '3600'
            - name: MONGODB_URI
              value: mongodb+srv://andrea:kelocura12345@andreallerena.hr5injm.mongodb.net/?retryWrites=true&w=majority&appName=ANDREALLERENA 
            - name: RABBIT_MQ_URI
              value: amqps://andrea:kelocura12345@b-fdb8dcd6-3136-4cdd-bc09-a6a5e266ea80.mq.us-east-1.amazonaws.com:5671