apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: andrea
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: mguay/ordering-app_orders
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: MONGODB_URI
              value: mongodb+srv://andrea:kelocura12345@andreallerena.hr5injm.mongodb.net/?retryWrites=true&w=majority&appName=ANDREALLERENA
            - name: RABBIT_MQ_URI
              value: amqps://andrea:kelocura12345@b-fdb8dcd6-3136-4cdd-bc09-a6a5e266ea80.mq.us-east-1.amazonaws.com:5671